services:
  - type: web
    name: doctors-appointment-backend
    env: node
    plan: free
    buildCommand: yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
